%define _prefix /opt/gled
%define svnv %(a=`svn info https://svn.gled.org/gled/trunk/gled-builder | grep Revision | awk '{print $2}'` ; echo ${a};)
%define mtest  0

Name:         gled
Version:      1.3
Release:      %{svnv}svn
License:      GPL
Vendor:       GLED Team
URL:          www.gled.org
Source0:      https://svn.gled.org/gled/trunk/gled-builder
Group:        Applications/Science
BuildRoot:    %{_tmppath}/%{name}-%{version}-root
Summary:      Generic Lightweight Environment for Distributed computing. 
# autogenerated dependencies deisabled, because require fltk-mt.so
AutoReqProv:  no

BuildRequires: gcc-c++, libstdc++-devel
BuildRequires: libX11-devel, libXpm-devel
#BuildRequires: xorg-x11-devel, xpm-devel
BuildRequires: libGL-devel, libGLU-devel
BuildRequires: zlib-devel, libpng-devel, libjpeg-devel, libtiff-devel
BuildRequires: gsl-devel
BuildRequires: pcre-devel
BuildRequires: freetype-devel
BuildRequires: openssl-devel
# BuildRequires: DevIL


BuildArchitectures: x86_64
ExclusiveArch: x86_64

Provides: gled
%description
    Gled is a C++ framework for rapid development of applications with support for GUI, 3D-graphics and distributed computing. 
    It extends the ROOT framework (standard data-analysis tool in high-energy physics) with mechanisms for object collection management & serialization,
    multi-threaded execution, GUI auto-generation (object browser & editor) and dynamic visualization (OpenGL).

    Distributed computing model of Gled is a hierarchy of nodes connected via TCP/IP sockets. 
    Gled provides authentication & access control, data exchange, proxying of object collections and remote method-call propagation & execution.

    Gled can be dynamically extended with library sets. Their creation is facilitated by a set of scripts for creation of user-code stubs.
    Simple tasks and application configuration can be efficiently done via the interactive C++ interpreter (CINT).

    Gled is used for development of programs in high energy physics and as a research tool in distributed and grid computing.

    Gled is the development platform for the Greed project.


%setup -q

%build
svn co https://svn.gled.org/gled/trunk/gled-builder
cd gled-builder
%{__autoconf}
./configure LIBSETS="GledCore Geom1 CmsGridViz"
%{__make}

%install
%{__mkdir_p} %{buildroot}/%{_prefix}
%{__rm} -rf %{buildroot}/%{_prefix}
%{__cp} -a %{_builddir}/gled-builder/install/ $RPM_BUILD_ROOT/%{_prefix}
%{__rm} -rf  $RPM_BUILD_ROOT/%{_prefix}/cache

%clean
rm -rf $RPM_BUILD_ROOT/

%files
%defattr(-,root,root)
%{_prefix}


