#!/usr/bin/perl

$DIR   = "gled-build";
$USER  = $ENV{'USER'};
$DEMOS = 1;

$SVN_BASE = "https://svn.gled.org/gled";

@def_libsets = qw{ GledCore Audio1 GTS Geom1 Numerica RootGeo Var1 };

while ($ARGV[0] =~ m/--([-\w]+)=([-\w]+)/) {
  my $var = uc $1;
  $var =~ s/-/_/g;
  my $val = $2;
  eval("\$$var = '$val';");
  shift @ARGV;
}

if ($#ARGV < 0) {
  print STDERR <<"FNORD";
usage: gled-build-checkout [OPTIONS] version [libsets]

  version = SVN path to gled-build, eg. 'trunk' or 'tags/v1-3-0'.
  libsets = Space-separated list of libsets, eg. 'GledCore Geom1'.
            If none are given, the following list is used:
            @def_libsets

  OPTIONS
    --dir=<co-dir>       $DIR
    --user=<svn-user>    $USER
    --demos=[0|1]        $DEMOS
FNORD
  exit 1;
}

$VER = shift @ARGV;

@LIBSETS = @ARGV;
if ($#LIBSETS < 0) {
  @LIBSETS = @def_libsets;
}

########################################################################

sub exec_or_die {
  my $cmd = shift;
  if($DRYRUN) {
    print "EXEC: $cmd\n";
  } else {
    my $ret = `$cmd`;
    die "$cmd died" if $?;
    return $ret
  }
}

sub system_or_die {
  my $cmd = shift;
  if($DRYRUN) {
    print "SYST: $cmd\n";
  } else {
    system "$cmd" and die "$cmd died";
  }    
}

########################################################################

$CO_CMD = "svn checkout --username $USER";
$UP_CMD = "svn update";

system_or_die("$CO_CMD $SVN_BASE/$VER/gled-build $DIR");

chdir $DIR;

system_or_die("$CO_CMD --non-recursive $SVN_BASE/$VER/libsets");
chdir "libsets";
for $ls (@LIBSETS) {
  system_or_die("$UP_CMD $ls");
}
chdir "..";
`ln -s libsets/* .`;

if ($DEMOS) {
  system_or_die("$CO_CMD --non-recursive $SVN_BASE/$VER/demos");
  chdir "demos";
  for $ls (@LIBSETS) {
    # do not die if given demo does not exist
    system "$UP_CMD $ls";
  }
  chdir "..";
}
