#!/usr/bin/perl

$DIR   = "gled-build";
$USER  = $ENV{'USER'};
$DEMOS = 1;

# !!! change to https !!!
$SVN_BASE = "http://svn.gled.org/gled";

while ($ARGV[0] =~ m/--([-\w]+)=([-\w]+)/) {
  my $var = uc $1;
  $var =~ s/-/_/g;
  my $val = $2;
  eval("\$$var = '$val';");
  shift @ARGV;
}

if ($#ARGV < 0) {
  print STDERR <<"FNORD";
usage: gled-build-checkout [OPTIONS] version [libsets]

  version = svn path to gled-build, eg. 'trunk' or 'tags/v1-3-0'
  libsets = space-separated list of libsets, eg. 'GledCore Geom1'

  OPTIONS
    --dir=<co-dir>       $DIR
    --user=<svn-user>    $USER
    --demos=[0|1]        $DEMOS
FNORD
  exit 1;
}

$VER = shift @ARGV;

########################################################################

sub exec_or_die {
  my $cmd = shift;
  if($DRYRUN) {
    print "EXEC: $cmd\n";
  } else {
    my $ret = `$cmd`;
    die "$cmd died" if $?;
    return $ret
  }
}

sub system_or_die {
  my $cmd = shift;
  if($DRYRUN) {
    print "SYST: $cmd\n";
  } else {
    system "$cmd" and die "$cmd died";
  }    
}

########################################################################

$CO_CMD = "svn co --username $USER";

system_or_die("$CO_CMD $SVN_BASE/$VER/gled-build $DIR");

chdir $DIR;

# !!! Modify this to take import lilbsets into libset/ ... when/if I
# modify the build infrastructure.

for $ls (@ARGV) {
  system_or_die("$CO_CMD $SVN_BASE/$VER/libsets/$ls");
}

if ($DEMOS) {
  system_or_die("$CO_CMD --non-recursive $SVN_BASE/$VER/demos");
  chdir demos;
  for $ls (@ARGV) {
    # do not die if given demo does not exist
    system "$CO_CMD $SVN_BASE/$VER/demos/$ls";
  }
}
