# $Header$
LIB_SET_NAME	= Geom1
LIB_SET_ID	= 2
REQUIRES_LIB_SETS = GledCore # add

BLESSED_DIRS	= Glasses
BASE_DIRS	= Stones Geom1 

DICT_DIRS	= Glasses Stones Geom1
VIEW_DIRS	= FL
VIEW_FL_DIRS	= FL

BASE_LD_LIBS    = -L${ROOTSYS}/lib -lPhysics -lIL -lILU

##### Targets #####

LIBSET_TARGETS := # define additional targets (libraires built by default)

include ${GLEDSYS}/make/make_base.inc

clean::
distclean::
