# $Header$

LIB_SET_NAME	:= Numerica
LIB_SET_ID	:= 3
REQUIRES_LIB_SETS := GledCore

# Nice, friendly woozies that don't need special treatment
BLESSED_DIRS	:= Glasses
BASE_DIRS	:= Stones Numerica 

DICT_DIRS	:= Glasses Stones Numerica
VIEW_FL_DIRS	:=
VIEW_DIRS	:=

##### Targets #####

LIBSET_TARGETS := # define additional targets (libraires built by default)

include ${GLEDSYS}/make/make_base.inc

# user targets go here; enumerate them in LIBSET_TARGETS

.PHONY:	libset_clean libset_distclean
# this is user-definable ... must clean all local stuff
libset_clean:
libset_distclean:
