# $Id$
LIB_SET_NAME	:= AliEnViz
LIB_SET_ID	:= 66
REQUIRES_LIB_SETS := GledCore Geom1 Var1

# Nice, friendly woozies that don't need special treatment
BLESSED_DIRS	:= Glasses
BASE_DIRS	:= Stones AliEnViz 

DICT_DIRS	:= Glasses Stones AliEnViz

VIEW_DIRS	:=
VIEW_FL_DIRS	:=

BASE_LD_LIBS    =

#--------------------------------------------------------------
include ${GLEDSYS}/make/make_base.inc
#--------------------------------------------------------------

#LIBSET_PREREQS +=
#LIBSET_TARGETS +=

# user targets go here; enumerate them in LIBSET_TARGETS

#--------------------------------------------------------------
include ${GLEDSYS}/make/make_targets.inc
#--------------------------------------------------------------
