// Preamble for SXrdClasses.h, generated by the extract-sxrd-classes.pl script.
//
// To build library by hand:
//   rootcint -f SXrdClasses_Dict.cxx -c -p SXrdClasses.h SXrdClasses_LinkDef.h
//   g++ -o libSXrdClasses.so -shared -fPIC `root-config --cflags` SXrdClasses.cxx SXrdClasses_Dict.cxx
// In root:
//   gSystem->Load("libSXrdClasses")
//   // or put it in rootrc
//
// For analysis of IOV data, stored in SXrdIoInfo structs, see function
// dump_xrdfar_tree_ioinfo().

#include "Rtypes.h"
class TTree;

void dump_xrdfar_tree_ioinfo(TTree *t, Long64_t ev);

